distributionType=bin
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.10.0/apache-maven-3.10.0-bin.zip
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.3/maven-wrapper-3.3.3.jar
wrapperVersion=3.3.3
wrapperSha256Sum=1ada66a0d65291f3b5c0e12f8860cc5d422da76c9f90313a2c0f1cd280ae8ede
