package space.seclume.oracle.jdbc;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import space.seclume.RoundTrips;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * The Oracle driver through JDBC, against a <b>real</b> instance.
 *
 * <p>What an application sees: {@code DriverManager.getConnection}, statements,
 * result sets, metadata. The protocol itself is checked elsewhere.
 *
 * <p>The URL carries no password, only where to find one.
 */
class LocalOracleJdbcTest {

    private static final String HOST =
            System.getProperty("seclume.oracle.host", "db.example.invalid");
    private static final int PORT = Integer.getInteger("seclume.oracle.port", 1521);
    private static final String USER =
            System.getProperty("seclume.oracle.user", "seclume_test");
    private static final String SERVICE =
            System.getProperty("seclume.oracle.service", "FREEPDB1");

    private static String url;

    @BeforeAll
    static void findTheServer() {
        Path password = null;
        for (Path candidate : List.of(Path.of(".local-oracle-password"),
                Path.of("..", ".local-oracle-password"))) {
            if (Files.exists(candidate)) {
                password = candidate.toAbsolutePath().normalize();
            }
        }
        Assumptions.assumeTrue(password != null, "no .local-oracle-password");
        try (Socket socket = new Socket()) {
            socket.connect(new InetSocketAddress(HOST, PORT), 2000);
        } catch (IOException e) {
            Assumptions.abort("no Oracle listener on " + HOST + ":" + PORT);
        }
        url = "jdbc:seclume:oracle://" + HOST + ":" + PORT + "/" + SERVICE
                + "?user=" + USER + "&provider=file&path="
                + password.toString().replace('\\', '/');
    }

    /** Drops a table if it is there - Oracle has no "if exists". */
    private static void drop(Connection connection, String table) {
        try (Statement statement = connection.createStatement()) {
            statement.execute("drop table " + table + " purge");   // purge: sonst zaehlt Oracle sie weiter
        } catch (SQLException e) {
            // ORA-00942: it was not there, which is what was wanted.
        }
    }

    /**
     * Generated keys - what every {@code @GeneratedValue} entity needs.
     *
     * <p>Oracle has no separate channel for them: the statement has to say
     * {@code returning <column> into :n}, and the value arrives in that bind.
     * The driver adds the clause and one output bind per column, and reads
     * what comes back in front of the answer - a {@code ROW_DATA} message
     * without any column description, whose shape is known only because the
     * driver chose the clause itself. All of it taken from a capture of the
     * reference client, not from guessing.
     */
    @Test
    void generatedKeysComeBackFromAnInsert() throws Exception {
        try (Connection connection = connect()) {
            drop(connection, "zl_keys");
            try (Statement statement = connection.createStatement()) {
                statement.execute("create table zl_keys ("
                        + "id number generated by default as identity primary key, "
                        + "name varchar2(50))");
            }
            try {
                try (PreparedStatement insert = connection.prepareStatement(
                        "insert into zl_keys (name) values (?)", new String[] {"id"})) {
                    insert.setString(1, "first");
                    assertEquals(1, insert.executeUpdate());
                    long first;
                    try (ResultSet keys = insert.getGeneratedKeys()) {
                        assertTrue(keys.next(), "no key came back");
                        first = keys.getLong(1);
                        assertTrue(first > 0, "the key was " + first);
                    }

                    insert.setString(1, "second");
                    insert.executeUpdate();
                    try (ResultSet keys = insert.getGeneratedKeys()) {
                        assertTrue(keys.next());
                        assertEquals(first + 1, keys.getLong("id"),
                                "the second key does not follow the first");
                    }
                }
            } finally {
                drop(connection, "zl_keys");
            }
        }
    }

    /** Without column names Oracle cannot do it, and the driver says so. */
    @Test
    void generatedKeysWithoutColumnNamesAreRefusedWithTheReason() throws Exception {
        try (Connection connection = connect()) {
            SQLException thrown = assertThrows(SQLException.class,
                    () -> connection.prepareStatement("insert into zl_keys (name) values (?)",
                            Statement.RETURN_GENERATED_KEYS));
            assertTrue(thrown.getMessage().contains("name them"), thrown.getMessage());
        }
    }

    /**
     * A big result is read in blocks, not all at once.
     *
     * <p>Oracle read in blocks all along - the driver simply fetched to the
     * end and kept everything. With a fetch size it stops after the first
     * block, and the memory of a large query is the memory of one block.
     *
     * <p>Unlike PostgreSQL this needs no transaction: an Oracle cursor belongs
     * to the session.
     */
    @Test
    void aFetchSizeReadsTheResultInBlocks() throws Exception {
        try (Connection connection = connect();
             PreparedStatement query = connection.prepareStatement(
                     "select level from dual connect by level <= 1000")) {
            query.setFetchSize(100);
            long before = RoundTrips.of(connection);
            int seen = 0;
            long sum = 0;
            try (ResultSet rows = query.executeQuery()) {
                while (rows.next()) {
                    seen++;
                    assertEquals(seen, rows.getInt(1), "the rows arrived out of order");
                    sum += rows.getInt(1);
                }
            }
            long spent = RoundTrips.of(connection) - before;
            assertEquals(1000, seen, "rows lost");
            assertEquals(500500L, sum, "the values changed");
            assertTrue(spent >= 10 && spent <= 12,
                    "ten blocks of a hundred rows, give or take the one that finds the "
                    + "end - but it was " + spent);
        }
    }

    /** Without a fetch size nothing changes: the driver reads to the end. */
    @Test
    void withoutAFetchSizeTheWholeResultIsRead() throws Exception {
        try (Connection connection = connect();
             PreparedStatement query = connection.prepareStatement(
                     "select level from dual connect by level <= 1000")) {
            int seen = 0;
            try (ResultSet rows = query.executeQuery()) {
                while (rows.next()) {
                    seen++;
                }
            }
            assertEquals(1000, seen);
        }
    }

    /**
     * A prepared query that runs again costs <b>one</b> round trip.
     *
     * <p>It cost two for a while, and nothing in the code said so: the
     * {@code al8i4} field that says how many rows the execute may bring back
     * was zero. On a first execution the server sends rows anyway; on a
     * re-execution of the same cursor it sends none, and the driver paid a
     * fetch for what should have come with the execute. A number, not a
     * feeling - which is why it is a test and not a comment.
     */
    @Test
    void aPreparedQueryThatRunsAgainCostsOneRoundTrip() throws Exception {
        try (Connection connection = connect();
             PreparedStatement query = connection.prepareStatement("select 1 from dual")) {
            try (ResultSet warmup = query.executeQuery()) {
                assertTrue(warmup.next());
            }
            long before = RoundTrips.of(connection);
            try (ResultSet rows = query.executeQuery()) {
                assertTrue(rows.next());
                assertEquals(1, rows.getInt(1));
            }
            assertEquals(1, RoundTrips.of(connection) - before,
                    "a second run must not pay for a fetch of its own");
        }
    }

    /** And a bigger result still arrives complete, row for row. */
    @Test
    void aPreparedQueryThatRunsAgainStillBringsEveryRow() throws Exception {
        try (Connection connection = connect();
             PreparedStatement query = connection.prepareStatement(
                     "select level from dual connect by level <= 250")) {
            for (int run = 1; run <= 3; run++) {
                int seen = 0;
                long sum = 0;
                try (ResultSet rows = query.executeQuery()) {
                    while (rows.next()) {
                        seen++;
                        sum += rows.getInt(1);
                    }
                }
                assertEquals(250, seen, "run " + run + " lost rows");
                assertEquals(250L * 251 / 2, sum, "run " + run + " changed the values");
            }
        }
    }

    /**
     * A result that runs away ends in an error that names the query - and the
     * connection is still usable afterwards, because the rest of the answer
     * was read to the end.
     */
    @Test
    void aResultLargerThanTheLimitIsRefused() throws Exception {
        String bounded = url + "&maxResultRows=10";
        try (Connection connection = DriverManager.getConnection(bounded);
             Statement statement = connection.createStatement()) {
            SQLException thrown = assertThrows(SQLException.class,
                    () -> statement.executeQuery(
                            "select level from dual connect by level <= 100"));
            assertEquals("54001", thrown.getSQLState());
            assertTrue(thrown.getMessage().contains("maxResultRows"), thrown.getMessage());
            try (ResultSet rows = statement.executeQuery("select 42 from dual")) {
                assertTrue(rows.next());
                assertEquals(42, rows.getInt(1));
            }
        }
    }

    /** Leaves the schema as it was found - see {@link OracleTestSchema}. */
    @AfterAll
    static void cleanUp() throws SQLException {
        if (url == null) {
            return;
        }
        try (Connection connection = connect()) {
            OracleTestSchema.clean(connection);
        }
    }

    private static Connection connect() throws SQLException {
        return DriverManager.getConnection(url);
    }

    /** The DriverManager finds the driver through META-INF/services. */
    @Test
    void connectsThroughTheDriverManager() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("select 1 + 1 from dual")) {
            assertTrue(result.next());
            assertEquals(2, result.getInt(1));
        }
    }

    /** Values through the JDBC accessors, including Oracle's number format. */
    @Test
    void readsValuesThroughTheAccessors() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement();
             ResultSet row = statement.executeQuery(
                     "select 42 as n, 1.5 as d, 'abc' as t from dual")) {
            assertTrue(row.next());
            assertEquals(42, row.getInt("n"));
            assertEquals(42L, row.getLong("n"));
            assertEquals(1.5, row.getDouble("d"));
            assertEquals("abc", row.getString("t"));
            assertEquals(0, new java.math.BigDecimal("1.5")
                    .compareTo(row.getBigDecimal("d")));
        }
    }

    /** NULL has to arrive as NULL, and wasNull has to say so. */
    @Test
    void readsNullValues() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement();
             ResultSet row = statement.executeQuery(
                     "select cast(null as number) as a, 1 as b from dual")) {
            assertTrue(row.next());
            assertEquals(0, row.getInt("a"));
            assertTrue(row.wasNull());
            assertEquals(1, row.getInt("b"));
            assertTrue(!row.wasNull());
        }
    }

    /** The column description an application asks for. */
    @Test
    void describesItsColumns() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement();
             ResultSet row = statement.executeQuery(
                     "select 42 as n, 'abc' as t from dual")) {
            ResultSetMetaData meta = row.getMetaData();
            assertEquals(2, meta.getColumnCount());
            assertEquals("N", meta.getColumnLabel(1), "Oracle upper-cases unquoted names");
            assertEquals("NUMBER", meta.getColumnTypeName(1));
            assertEquals(Types.CHAR, meta.getColumnType(2),
                    "a literal in a query is a CHAR, not a VARCHAR");
        }
    }

    /** A failing statement has to fail, with Oracle's number in the exception. */
    @Test
    void reportsAFailingStatement() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            SQLException failure = assertThrows(SQLException.class,
                    () -> statement.executeQuery("select * from zl_does_not_exist"));
            assertEquals(942, failure.getErrorCode());
            // The connection has to survive it.
            try (ResultSet row = statement.executeQuery("select 1 from dual")) {
                assertTrue(row.next());
            }
        }
    }

    /**
     * Tables and columns out of the catalog.
     *
     * <p>This is also the test for a rule that cost an afternoon: a column
     * that is an untyped {@code null} in the select list carries <b>no bytes
     * at all</b> in the row. Every metadata query is full of
     * {@code null as "SOMETHING"}, so a reader that expects one value per
     * column reads all of them shifted - and gets plausible wrong data rather
     * than an error.
     */
    @Test
    void describesTablesAndColumns() throws Exception {
        try (Connection connection = connect()) {
            DatabaseMetaData meta = connection.getMetaData();
            assertEquals("Oracle", meta.getDatabaseProductName());
            assertNotNull(meta.getDatabaseProductVersion());

            List<String> tables = new ArrayList<>();
            try (ResultSet found = meta.getTables(null, "SYS", "DUAL", null)) {
                while (found.next()) {
                    tables.add(found.getString("TABLE_NAME"));
                }
            }
            assertTrue(tables.contains("DUAL"), "DUAL was not found: " + tables);

            // getColumns is checked separately, and currently disabled - see
            // theColumnListIsStillEmpty().
        }
    }

    /**
     * The full column list of a table - the query that used to come back
     * empty.
     *
     * <p>Three faults sat on top of each other here, and every one of them
     * cost rows without raising anything: the column description of a real
     * table column was read with two fields too many, the bit vector between
     * rows was read with a length that is not sent, and a {@code LONG} -
     * {@code COLUMN_DEF} is one - is described with a buffer size of zero like
     * an untyped null and still sends bytes. On top of that the answer to a
     * wide query holds the description and no rows at all, so the rows have to
     * be fetched even though the first block came back empty.
     */
    @Test
    void listsTheColumnsOfATable() throws Exception {
        try (Connection connection = connect()) {
            Map<String, Integer> columns = new HashMap<>();
            try (ResultSet found = connection.getMetaData()
                    .getColumns(null, "SYS", "ALL_USERS", null)) {
                while (found.next()) {
                    columns.put(found.getString("COLUMN_NAME"), found.getInt("DATA_TYPE"));
                }
            }
            assertEquals(Types.VARCHAR, columns.get("USERNAME"));
            // NUMERIC and not INTEGER: USER_ID is a NUMBER without a declared
            // precision, and only a declared one small enough makes it an int.
            assertEquals(Types.NUMERIC, columns.get("USER_ID"));
            assertEquals(13, columns.size(), "every column, not just the first block");
        }
    }

    /**
     * DDL - and what it took to make it work.
     *
     * <p>A {@code create table} used to answer {@code ORA-01003, no statement
     * parsed}, and the message was exact: the server had parsed the text and
     * then run it <b>zero times</b>. The execute call carries a vector of
     * thirteen numbers in which a statement that returns no rows has to say
     * one iteration, and the driver sent the shape of a query, where that
     * field is zero and a flag further along is set instead.
     */
    @Test
    void runsDdl() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("create table zl_jdbc (id number(9) primary key)");
            statement.execute("drop table zl_jdbc");
        }
    }

    /**
     * Auto-commit has to commit - and switching it off has to hold back.
     *
     * <p>Read over a <b>second</b> connection, because that is the only way to
     * tell a commit from a write that is merely visible to its own session.
     * This is the test for a bug that lost data quietly: the driver reported
     * auto-commit as on, as JDBC requires, and never set the bit that makes
     * Oracle commit - so everything an application wrote without calling
     * {@code commit} itself was rolled back when the connection closed.
     */
    @Test
    void autoCommitCommitsAndTurningItOffHoldsBack() throws Exception {
        try (Connection writer = connect()) {
            try (Statement statement = writer.createStatement()) {
                statement.execute("create table zl_commit (n number(9))");
            }
            try {
                try (PreparedStatement insert = writer.prepareStatement(
                        "insert into zl_commit values (?)")) {
                    insert.setInt(1, 1);
                    insert.executeUpdate();              // auto-commit is on
                }
                assertEquals(1, countOver(1), "auto-commit did not commit");

                writer.setAutoCommit(false);
                try (PreparedStatement insert = writer.prepareStatement(
                        "insert into zl_commit values (?)")) {
                    insert.setInt(1, 2);
                    insert.executeUpdate();
                }
                assertEquals(1, countOver(2),
                        "a row appeared although the transaction was still open");
                writer.commit();
                assertEquals(2, countOver(2), "commit did not commit");

                try (PreparedStatement insert = writer.prepareStatement(
                        "insert into zl_commit values (?)")) {
                    insert.setInt(1, 3);
                    insert.executeUpdate();
                }
                writer.rollback();
                assertEquals(2, countOver(3), "rollback did not roll back");
            } finally {
                writer.setAutoCommit(true);
                try (Statement statement = writer.createStatement()) {
                    statement.execute("drop table zl_commit");
                }
            }
        }
    }

    /** How many rows a <b>different</b> connection can see. */
    private static int countOver(int ignored) throws SQLException {
        try (Connection reader = connect();
             Statement statement = reader.createStatement();
             ResultSet found = statement.executeQuery("select count(*) from zl_commit")) {
            found.next();
            return found.getInt(1);
        }
    }

    /**
     * A batch as one call, and many executions on one cursor.
     *
     * <p>Two things are checked here that used to be broken in opposite ways.
     * The batch goes over as a <b>single</b> array execution - the statement
     * once, the values five hundred times - instead of five hundred round
     * trips. And every execution used to have the server parse the text anew,
     * which opens a <b>new cursor</b> each time: after a few hundred the
     * connection died with {@code ORA-01000, maximum open cursors exceeded}.
     * The four hundred queries in the second half are there to make that come
     * back if the cursor is ever forgotten again.
     */
    @Test
    void runsABatchAsOneCallAndKeepsOneCursor() throws Exception {
        int rows = 500;
        try (Connection connection = connect()) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("create table zl_array (n number(9), t varchar2(40))");
            }
            try {
                try (PreparedStatement insert = connection.prepareStatement(
                        "insert into zl_array (n, t) values (?, ?)")) {
                    for (int i = 0; i < rows; i++) {
                        insert.setInt(1, i);
                        insert.setString(2, "row-" + i);
                        insert.addBatch();
                    }
                    int[] counts = insert.executeBatch();
                    assertEquals(rows, counts.length, "one count per row");
                    for (int count : counts) {
                        assertEquals(1, count);
                    }
                }
                connection.commit();
                try (Statement statement = connection.createStatement();
                     ResultSet found = statement.executeQuery(
                             "select count(*), min(t), max(n) from zl_array")) {
                    assertTrue(found.next());
                    assertEquals(rows, found.getInt(1));
                    assertEquals("row-0", found.getString(2));
                    assertEquals(rows - 1, found.getInt(3));
                }

                // Well past the default open_cursors of 300.
                try (PreparedStatement query = connection.prepareStatement(
                        "select count(*) from zl_array where n > ?")) {
                    for (int i = 0; i < 400; i++) {
                        query.setInt(1, i);
                        try (ResultSet found = query.executeQuery()) {
                            assertTrue(found.next());
                            assertEquals(rows - i - 1, found.getInt(1));
                        }
                    }
                }
            } finally {
                try (Statement statement = connection.createStatement()) {
                    statement.execute("drop table zl_array");
                }
            }
        }
    }

    /**
     * Bind variables, end to end: types in, types out, and the counts the
     * server reports for a statement that changes rows.
     *
     * <p>Oracle needs no separate prepare call - the text and the values
     * travel in one message - so this costs no round trip more than a plain
     * statement, and no value ever enters the statement text.
     */
    @Test
    void runsPreparedStatements() throws Exception {
        try (Connection connection = connect()) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("create table zl_prepared (n number(9), t varchar2(40), "
                        + "d date, r raw(8))");
            }
            try {
                try (PreparedStatement insert = connection.prepareStatement(
                        "insert into zl_prepared (n, t, d, r) values (?, ?, ?, ?)")) {
                    insert.setInt(1, 1);
                    // A question mark inside a literal is text, and so is the
                    // apostrophe doubled in front of it. Both go through the
                    // rewriter, and neither becomes a bind variable.
                    insert.setString(2, "it's a test? yes");
                    insert.setDate(3, java.sql.Date.valueOf("2026-09-08"));
                    insert.setBytes(4, new byte[] {1, 2, 3});
                    assertEquals(1, insert.executeUpdate(), "the server counts the row");

                    insert.setInt(1, 2);
                    insert.setString(2, null);
                    insert.setNull(3, Types.DATE);
                    insert.setNull(4, Types.VARBINARY);
                    assertEquals(1, insert.executeUpdate());
                }
                try (PreparedStatement batch = connection.prepareStatement(
                        "insert into zl_prepared (n, t) values (?, ?)")) {
                    for (int i = 10; i < 14; i++) {
                        batch.setInt(1, i);
                        batch.setString(2, "row" + i);
                        batch.addBatch();
                    }
                    assertArrayEquals(new int[] {1, 1, 1, 1}, batch.executeBatch());
                }
                connection.commit();

                try (PreparedStatement select = connection.prepareStatement(
                        "select n, t, d, r from zl_prepared where n <= ? order by n")) {
                    select.setInt(1, 2);
                    try (ResultSet rows = select.executeQuery()) {
                        assertTrue(rows.next());
                        assertEquals(1, rows.getInt("n"));
                        assertEquals("it's a test? yes", rows.getString("t"));
                        assertEquals(java.sql.Date.valueOf("2026-09-08"), rows.getDate("d"));
                        assertArrayEquals(new byte[] {1, 2, 3}, rows.getBytes("r"));

                        assertTrue(rows.next());
                        assertEquals(2, rows.getInt("n"));
                        assertNull(rows.getString("t"));
                        assertNull(rows.getDate("d"));
                        assertFalse(rows.next());
                    }
                }
                try (PreparedStatement update = connection.prepareStatement(
                        "update zl_prepared set t = ? where n = ?")) {
                    update.setString(1, "one");
                    update.setInt(2, 1);
                    assertEquals(1, update.executeUpdate());
                }
                try (PreparedStatement delete = connection.prepareStatement(
                        "delete from zl_prepared where n = ?")) {
                    delete.setInt(1, 2);
                    assertEquals(1, delete.executeUpdate());
                }
                connection.commit();
                try (Statement statement = connection.createStatement();
                     ResultSet count = statement.executeQuery(
                             "select count(*) from zl_prepared")) {
                    assertTrue(count.next());
                    assertEquals(5, count.getInt(1));
                }
            } finally {
                try (Statement statement = connection.createStatement()) {
                    statement.execute("drop table zl_prepared");
                }
            }
        }
    }

    // ---- procedure calls --------------------------------------------------

    /**
     * An {@code OUT} parameter, through the anonymous block and an output
     * bind - the mechanism Oracle actually has, rather than a translation
     * into something else.
     */
    @Test
    void callsAProcedureAndReadsAnOutputParameter() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("create or replace procedure zl_double(n in number, "
                    + "doubled out number) as begin doubled := n * 2; end;");
            try (CallableStatement call = connection.prepareCall("{call zl_double(?, ?)}")) {
                call.setInt(1, 21);
                call.registerOutParameter(2, Types.INTEGER);
                call.execute();
                assertEquals(42, call.getInt(2));
                assertFalse(call.wasNull());
            }
            statement.execute("drop procedure zl_double");
        }
    }

    /** An {@code IN OUT} parameter: the value goes in and comes back changed. */
    @Test
    void callsAProcedureWithAnInOutParameter() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("create or replace procedure zl_grow(n in out number) as "
                    + "begin n := n + 5; end;");
            try (CallableStatement call = connection.prepareCall("{call zl_grow(?)}")) {
                call.registerOutParameter(1, Types.INTEGER);
                call.setInt(1, 37);
                call.execute();
                assertEquals(42, call.getInt(1));
            }
            statement.execute("drop procedure zl_grow");
        }
    }

    /**
     * A text output beside a number one.
     *
     * <p>This is the case the typed output bind exists for: described as a
     * NUMBER - which is all the driver could do before - a VARCHAR2 comes
     * back as bytes that decode into nonsense rather than into an error.
     */
    @Test
    void callsAProcedureWithATextOutputAndANumberOutput() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("create or replace procedure zl_split(whole in varchar2, "
                    + "head out varchar2, size_out out number) as begin "
                    + "head := substr(whole, 1, instr(whole, '-') - 1); "
                    + "size_out := length(whole); end;");
            try (CallableStatement call = connection.prepareCall("{call zl_split(?, ?, ?)}")) {
                call.setString(1, "left-right");
                call.registerOutParameter(2, Types.VARCHAR);
                call.registerOutParameter(3, Types.INTEGER);
                call.execute();
                assertEquals("left", call.getString(2));
                assertEquals(10, call.getInt(3));
            }
            statement.execute("drop procedure zl_split");
        }
    }

    /**
     * A function: {@code begin :1 := f(:2); end;}, so the return value is
     * simply the output bind at position one and nothing shifts.
     */
    @Test
    void callsAFunctionAndReadsItsReturnValue() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("create or replace function zl_triple(n in number) "
                    + "return number as begin return n * 3; end;");
            try (CallableStatement call = connection.prepareCall("{? = call zl_triple(?)}")) {
                call.registerOutParameter(1, Types.INTEGER);
                call.setInt(2, 14);
                call.execute();
                assertEquals(42, call.getInt(1));
            }
            statement.execute("drop function zl_triple");
        }
    }

    /** An output that came back NULL says so rather than reading as zero. */
    @Test
    void anOutputThatIsNullSaysSo() throws Exception {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("create or replace procedure zl_nothing(n out number) as "
                    + "begin n := null; end;");
            try (CallableStatement call = connection.prepareCall("{call zl_nothing(?)}")) {
                call.registerOutParameter(1, Types.INTEGER);
                call.execute();
                assertEquals(0, call.getInt(1));
                assertTrue(call.wasNull());
            }
            statement.execute("drop procedure zl_nothing");
        }
    }
}
