-- And in Oracle's. "number(19)" is what a Java long maps to, and the identity
-- column is the 12c form the driver returns keys for.
create table zl_customer (
    id       number(19) generated by default as identity primary key,
    name     varchar2(100) not null,
    email    varchar2(200) not null unique
);

create table zl_order (
    id          number(19) generated by default as identity primary key,
    customer_id number(19) not null,
    placed_at   timestamp not null,
    total       number(12, 2) not null,
    constraint zl_order_customer_fk foreign key (customer_id) references zl_customer (id)
);

create index zl_order_customer on zl_order (customer_id);
