-- The entity shapes: inheritance in all three strategies, composite keys in
-- both spellings, the collection mappings, a shared key and a second table.
-- As with V3 the DDL is Hibernate's own for this dialect, taken from its
-- schema generator rather than written here, so that ddl-auto=validate
-- compares like with like.
create sequence zl_payment_seq start with 1 increment by 1;
create table zl_book (id number(19,0) generated by default as identity, isbn varchar2(20 char) not null unique, title varchar2(120 char) not null, primary key (id));
create table zl_book_detail (book_id number(19,0) not null, summary varchar2(500 char), primary key (book_id));
create table zl_invoice (issued_on date not null, net number(12,2), id number(19,0) not null, doc_no varchar2(40 char) not null, primary key (id));
create table zl_keys (next_value number(19,0), key_name varchar2(255 char) not null, primary key (key_name));
insert into zl_keys(key_name, next_value) values ('zl_doc',0);
create table zl_payment (amount number(12,2) not null, id number(19,0) not null, paid_at timestamp(9) not null, primary key (id));
create table zl_payment_bank (payment_id number(19,0) not null, iban varchar2(34 char), primary key (payment_id));
create table zl_payment_card (last_four varchar2(4 char), payment_id number(19,0) not null, primary key (payment_id));
create table zl_player (id number(19,0) generated by default as identity, team_id number(19,0), label varchar2(60 char) not null, primary key (id));
create table zl_player_profile (player_id number(19,0) not null, bio varchar2(200 char), primary key (player_id));
create table zl_player_skill (player_id number(19,0) not null, skill_id number(19,0) not null, primary key (player_id, skill_id));
create table zl_receipt (issued_on date not null, id number(19,0) not null, doc_no varchar2(40 char) not null, cashier varchar2(60 char), primary key (id));
create table zl_seat (seat_row number(10,0) not null, section_name varchar2(20 char) not null, note varchar2(60 char), primary key (seat_row, section_name));
create table zl_skill (id number(19,0) generated by default as identity, label varchar2(40 char) not null, primary key (id));
create table zl_team (id number(19,0) generated by default as identity, label varchar2(60 char) not null, primary key (id));
create table zl_team_tag (team_id number(19,0) not null, tag varchar2(30 char), unique (team_id, tag));
create table zl_ticket (seat_no number(10,0) not null, event_name varchar2(40 char) not null, holder varchar2(60 char), primary key (seat_no, event_name));
create table zl_vehicle (payload number(10,2), seats number(10,0), id number(19,0) generated by default as identity, kind varchar2(16 char) not null check ((kind in ('CAR','TRUCK'))), label varchar2(60 char) not null, primary key (id));
alter table zl_book_detail add constraint FKg91iycnplnkkgutqt9yt622h0 foreign key (book_id) references zl_book;
alter table zl_payment_bank add constraint FKsqd8t5u525nj7956qkga74lvb foreign key (payment_id) references zl_payment;
alter table zl_payment_card add constraint FKpll1m9xgv8yy3vboalt5ntosy foreign key (payment_id) references zl_payment;
alter table zl_player add constraint FKmaujo0aivm1abdepy0mdo2pnc foreign key (team_id) references zl_team;
alter table zl_player_profile add constraint FKst9gwteqf9b6tc8cn67yda8kv foreign key (player_id) references zl_player;
alter table zl_player_skill add constraint FKsbjn3ne1ovvl001xydi9wukp1 foreign key (skill_id) references zl_skill;
alter table zl_player_skill add constraint FK1p905fksonjhyufe4ssnj9s6b foreign key (player_id) references zl_player;
alter table zl_team_tag add constraint FK4mf41b5c7vrcct0sbwjbqlcc4 foreign key (team_id) references zl_team;
