-- For the JdbcTemplate and transaction tests: plain tables no entity maps,
-- so that what is under test is Spring JDBC and the driver, not Hibernate.
create table sp_ledger (
    id      number(10) primary key,
    note    varchar2(200),
    amount  number(12, 2),
    created timestamp
);

create table sp_ledger_auto (
    id   number(10) generated by default as identity primary key,
    note varchar2(200)
);
