-- Hibernate edge cases: a JSON column, character and binary LOBs - as plain
-- values and as java.sql.Clob/Blob written from a stream - and a counter
-- that a @Formula reads.
create table zl_note (id number(19,0) generated by default as identity, title varchar2(80 char), words number(10,0) not null, attributes json, body clob, data blob, script clob, picture blob, primary key (id));
