-- The migration Flyway runs through the seclume driver. Deliberately ordinary
-- SQL: what is being tested is the driver, not the schema.
create table zl_customer (
    id       bigint generated by default as identity primary key,
    name     varchar(100) not null,
    email    varchar(200) not null unique
);

create table zl_order (
    id          bigint generated by default as identity primary key,
    customer_id bigint not null references zl_customer (id),
    placed_at   timestamp not null,
    total       numeric(12, 2) not null
);

create index zl_order_customer on zl_order (customer_id);
