-- For the JdbcTemplate and transaction tests: plain tables no entity maps,
-- so that what is under test is Spring JDBC and the driver, not Hibernate.
create table sp_ledger (
    id      int primary key,
    note    varchar(200),
    amount  numeric(12, 2),
    created timestamp
);

create table sp_ledger_auto (
    id   int generated by default as identity primary key,
    note varchar(200)
);
