-- Hibernate edge cases: a JSON column, character and binary LOBs - as plain
-- values and as java.sql.Clob/Blob written from a stream - and a counter
-- that a @Formula reads.
create table zl_note (id bigint generated by default as identity, title varchar(80), words integer not null, attributes jsonb, body oid, data oid, script oid, picture oid, primary key (id));
